drop table if exists app_user;
create table app_user (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name varchar(255) not null,
    password varchar(255) not null,
    email varchar(255) not null
);
drop table if exists student;
create table if not exists student (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade int not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    age int not null,
    average_rating float not null
);